from pydantic import BaseModel, Field
from datetime import datetime

class PredictionResponse(BaseModel):
    prediction: float = Field(
        ..., 
        description="Predicted house price generated by the ML model.",
        example=245000.5
    )
    model_version: str = Field(
        ..., 
        description="MLflow model version or run ID used for prediction.",
        example="a8f3c2d91e4b4f2c"
    )
    timestamp: datetime = Field(
        ..., 
        description="UTC timestamp when the prediction was generated.",
        example="2026-06-02T10:30:00Z"
    )